

spring.application.name=comunicacao
spring.datasource.url=jdbc:postgresql://localhost:5432/comunicacao_api
spring.datasource.username=postgres
spring.datasource.password=accessdatabase
spring.jpa.hibernate.ddl-auto=create


spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

server.port=8087